# Generated by Django 6.0.7 on 2026-07-25 18:02

import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=pipeline.models.document_upload_path),
        ),
    ]
